STACK_NAME : Observability
CODE_LOCATION : src/code
APP_NAME_TAG : ObserveHack
MODULE_NAME_TAG : ObserveHack
LAMBDA_LAYERS_BUILD:
  - opensearch
ASSET_LOCATION : src/assets
INIT_SCRIPT: src/template/cdk_app/ec2_init.sh
CLOUDWATCH_AGENT_CONFIG: src/template/cdk_app/cloudwatch_agent_config.json
INSTANCE_STATIC_IP: 10.104.146.219
NGINX_APPS:
  nexusapp: 80
  nobleapp: 80
